name: Go
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    name: Test with Go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.16, 1.17]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Set up Go 
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: ./scripts/runUnitTests.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Lint
      run: |
        mkdir ./bin
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b ./bin v1.21.0
        export PATH="$(pwd)/bin:$PATH"
        ./scripts/runLint.sh
